rules:
################################################################################
# 1️⃣ CODE INJECTION / EVAL / FUNCTION
################################################################################
  - id: js-dangerous-eval-user-input
    message: >
      Sử dụng eval()/Function() với dữ liệu động hoặc dữ liệu người dùng
      có thể dẫn tới Code Injection (CWE-95).
    severity: ERROR
    languages: [javascript, typescript]

    patterns:
      - pattern-either:
          - pattern: eval($X)
          - pattern: Function($X)
      - metavariable-regex:
          metavariable: $X
          regex: (?i)(req\.|request\.|input|data|body|query|params)

    pattern-not: eval("...")

    fix: |
      // Tránh eval()/Function().
      // Gợi ý:
      // - Dùng JSON.parse nếu parse dữ liệu
      // - Dùng logic xử lý cụ thể thay vì thực thi chuỗi
      JSON.parse($X)

    metadata:
      category: security
      cwe: CWE-95
      owasp: A03:2021-Injection
      impact: critical
      confidence: high

################################################################################
# 2️⃣ COMMAND INJECTION (Node.js)
################################################################################
  - id: js-command-injection
    message: >
      Dữ liệu người dùng được truyền trực tiếp vào command execution
      có thể dẫn tới Command Injection (CWE-78).
    severity: ERROR
    languages: [javascript]

    patterns:
      - pattern-either:
          - pattern: require("child_process").exec($CMD)
          - pattern: require("child_process").execSync($CMD)
          - pattern: require("child_process").spawn($CMD)
      - metavariable-regex:
          metavariable: $CMD
          regex: (?i)(req\.|request\.|input|body|query|params)

    metadata:
      category: security
      cwe: CWE-78
      owasp: A03:2021-Injection
      impact: critical
      confidence: high

################################################################################
# 3️⃣ DANGEROUS TIMER APIs (XSS / CODE EXEC)
################################################################################
  - id: js-dangerous-settimeout
    message: >
      setTimeout/setInterval với chuỗi có thể dẫn tới code execution.
    severity: ERROR
    languages: [javascript]

    patterns:
      - pattern-either:
          - pattern: setTimeout($X, ...)
          - pattern: setInterval($X, ...)
      - metavariable-regex:
          metavariable: $X
          regex: (?i)(req\.|input|data|query|params)

    metadata:
      category: security
      cwe: CWE-95
      confidence: medium

################################################################################
# 4️⃣ HARD-CODED SECRETS
################################################################################
  - id: js-hardcoded-secret
    message: >
      Phát hiện secret hardcoded trong source code.
      Không nên commit secret trực tiếp.
    severity: ERROR
    languages: [javascript, typescript]

    patterns:
      - pattern: const $KEY = "$SECRET"
      - metavariable-regex:
          metavariable: $SECRET
          regex: (?i)(api[_-]?key|secret|token|password|pwd)

    metadata:
      category: secrets
      cwe: CWE-798
      confidence: medium

################################################################################
# 5️⃣ INSECURE DESERIALIZATION
################################################################################
  - id: js-insecure-deserialization
    message: >
      Deserialization dữ liệu không tin cậy có thể dẫn tới RCE.
    severity: ERROR
    languages: [javascript]

    patterns:
      - pattern-either:
          - pattern: JSON.parse($X)
          - pattern: eval($X)
      - metavariable-regex:
          metavariable: $X
          regex: (?i)(req\.|request\.|input|body|query|params)

    metadata:
      category: security
      cwe: CWE-502
      confidence: high

################################################################################
# 6️⃣ PATH TRAVERSAL
################################################################################
  - id: js-path-traversal
    message: >
      Sử dụng path từ user input có thể dẫn tới Path Traversal.
    severity: ERROR
    languages: [javascript]

    patterns:
      - pattern: fs.readFile($P, ...)
      - metavariable-regex:
          metavariable: $P
          regex: (?i)(req\.|input|body|query|params)

    metadata:
      category: security
      cwe: CWE-22
      confidence: high
